name: test-build

on:
  push:
    branches: [ develop, master ]
    paths:
      - "package/**"
  pull_request:
    branches: [ develop, master ]
    paths:
      - "package/**"

defaults:
  run:
    working-directory: ./package

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: yarn test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build library
      